# Generated by Django 5.2.8 on 2025-11-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_vehiculo', models.CharField(db_comment='Aca se introduce el color del vehiculo ej: azul, rojo etc', max_length=50)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='EstadoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_espacio_parqueo', models.CharField(db_comment='Aca apareceria el estado del espacio en el cual esta el vehiculo el cual podra ser libre u ocupado', max_length=50)),
            ],
            options={
                'db_table': 'estado_espacio',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_vehiculo', models.CharField(db_comment='Aca va la marca de la que es el vehiculo ej: Chevrolet, Pulsar etc', max_length=50)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(db_comment='Aca iria el valor de la hora teniendo en cuenta el tipo de vehiculo', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tarifa',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_usuario', models.CharField(db_comment='Aca se introduce el tipo del usuario ej: Administrador o externo', max_length=100)),
            ],
            options={
                'db_table': 'Tipo_Usuario',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_vehiculo', models.CharField(db_comment='Aca se introduce cual es el tipo de vehiculo ej: Carro o Moto', max_length=50)),
            ],
            options={
                'db_table': 'tipo_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_comment='Es el codigo del espacio, cada espacio tiene un codigo distinto', max_length=20, unique=True)),
                ('idestado_espacio', models.ForeignKey(blank=True, db_column='idestado_espacio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.estadoespacio')),
            ],
            options={
                'db_table': 'espacio',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_vehiculo', models.CharField(db_comment='Aca iria el modelo del cual es la marca del vehiculo ej: spark gt, ns200 etc', max_length=50)),
                ('idmarca', models.ForeignKey(blank=True, db_column='idmarca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.marca')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvehiculo', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(db_comment='Aca iria la fecha en la que el vehiculo ingreso al parqueadero ')),
                ('hora_ingreso', models.TimeField(db_comment='Aca iria la hora en la que ingreso el vehiculo al parqueadero')),
                ('fecha_salida', models.DateField(db_comment='Aca va la fecha en la que el vehiculo salio del parqueadero')),
                ('hora_salida', models.TimeField(db_comment='Aca va la hora exacta en la que el vehiculo salio del parqueadero')),
                ('idespacio', models.ForeignKey(blank=True, db_column='idespacio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.espacio')),
            ],
            options={
                'db_table': 'registro',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.DecimalField(db_comment='Aca va el monto de pago total', decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(db_comment='Esta es la fecha en la que el usuario realizo el pago')),
                ('idregistro', models.ForeignKey(blank=True, db_column='idregistro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.registro')),
                ('idtarifa', models.ForeignKey(blank=True, db_column='idtarifa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.tarifa')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.AddField(
            model_name='tarifa',
            name='idtipo_vehiculo',
            field=models.ForeignKey(blank=True, db_column='idtipo_vehiculo', db_comment='Esta es la llave foranea idtipo_vehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.tipovehiculo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_comment='Aca se introduce el nombre del usuario', max_length=100)),
                ('numero_identificacion', models.CharField(db_comment='Aca se introduce el numero de identificaci¾n del usuario', max_length=100, unique=True)),
                ('correo', models.CharField(db_comment='Aca se introduce el correo del usuario', max_length=100)),
                ('celular', models.CharField(blank=True, db_comment='Aca se introduce el celular del usuario', max_length=20, null=True)),
                ('idtipo_usuario', models.ForeignKey(blank=True, db_column='idtipo_usuario', db_comment='Esta es la llave foranea idTipo_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_comment='Aca iria la placa de cada vehiculo', max_length=20, unique=True)),
                ('idcolor', models.ForeignKey(blank=True, db_column='idcolor', db_comment='Esta es la llave foranea idcolor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.color')),
                ('idmarca', models.ForeignKey(blank=True, db_column='idmarca', db_comment='Esta es la llave foranea idmarca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.marca')),
                ('idtipo_vehiculo', models.ForeignKey(blank=True, db_column='idtipo_vehiculo', db_comment='Esta es la llave foranea idtipo_vehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.tipovehiculo')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', db_comment='Esta es la llave foranea idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appregistro.usuario')),
            ],
            options={
                'db_table': 'vehiculo',
                'db_table_comment': 'esta tabla es de muchos con muchos',
            },
        ),
    ]
