# Generated by Django 5.2.6 on 2025-09-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apppagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('PSE', 'PSE'), ('Efectivo', 'Efectivo')], max_length=20),
        ),
    ]
