# Generated by Django 5.2.6 on 2025-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apppagos', '0002_remove_usuario_email_remove_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('pse', 'PSE'), ('tarjeta', 'Tarjeta')], max_length=20),
        ),
    ]
