# Generated by Django 5.2.6 on 2025-09-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appregistro', '0002_alter_vehiculo_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Appregistro.vehiculo')),
            ],
        ),
    ]
