# Generated by Django 5.2.6 on 2025-09-26 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appregistro', '0002_alter_vehiculo_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Appregistro.vehiculo')),
            ],
        ),
    ]
